class Country 
  COUNTRIES = [ "Afghanistan", "Albania", "Algeria", "Andorra",
                "Angola", "Antigua and Barbuda", "Argentina",
                "Armenia", "Australia", "Austria", "Azerbaijan",
                "Bahamas, The ", "Bahrain", "Bangladesh",
                "Barbados", "Belarus", "Belgium", "Belize",
                "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", 
                "Botswana", "Brazil", "Brunei",
                "Bulgaria", "Burkina Faso", "Burma", "Burundi",
                "Cambodia", "Cameroon", "Canada", "Cape Verde",
                "Central African Republic", "Chad", "Chile",
                "China", "Colombia", "Comoros", "Congo (Brazzaville)", 
                "Congo (Kinshasa)", "Costa Rica",
                "Croatia", "Cuba", "Cyprus", "Czech Republic",
                "Denmark", "Djibouti", "Dominica", "Dominican Republic", 
                "Ecuador", "Egypt", "El Salvador",
                "Equatorial Guinea", "Eritrea", "Estonia",
                "Ethiopia", "Republic of Ethiopia", "Fiji",
                "Finland", "France", "Gabon", "Gambia, The",
                "Georgia", "Germany", "Ghana", "Greece", "Grenada",
                "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
                "Republic of Guyana", "Haiti", "Holy See",
                "Honduras", "Hungary", "Iceland", "India",
                "Indonesia", "Iran", "Iraq", "Ireland", "Israel",
                "Italy", "Jamaica", "Japan", "Jordan", "Kingdom of Jordan", 
                "Kazakhstan", "Kenya", "Kiribati", "Korea, North", 
                "Korea, South", "Kosovo", "Kuwait",
                "Kyrgyzstan", "Laos", "Democratic Republic",
                "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
                "Liechtenstein", "Lithuania", "Luxembourg",
                "Macedonia", "Madagascar", "Malawi", "Malaysia",
                "Maldives", "Mali", "Malta", "Marshall Islands",
                "Mauritania", "Mauritius", "Mexico", "Micronesia,",
                "Federated States of of Micronesia", "Moldova",
                "Monaco", "Mongolia", "Montenegro", "Morocco",
                "Mozambique", "Namibia", "Nauru", "Nepal",
                "Netherlands", "New Zealand", "Nicaragua", "Niger",
                "Nigeria", "Norway", "Oman", "Pakistan", "Palau",
                "Panama", "Papua New Guinea", "Paraguay", "Peru",
                "Philippines", "Poland", "Portugal", "Qatar",
                "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", 
                "Saint Lucia", "Saint Vincent and", "the Grenadines", 
                "Samoa", "San Marino", "Sao Tome and Principe", 
                "Saudi Arabia", "Senegal", "Serbia",
                "Republic of Serbia", "Belgrade", "Seychelles",
                "Sierra Leone", "Singapore", "Slovakia",
                "Slovenia", "Solomon Islands", "Somalia", 
                "South Africa", "South Sudan", "Spain", "Sri Lanka",
                "Republic of Sri Lanka", "Sudan", "Suriname",
                "Swaziland", "Lobamba (legislative)", "Sweden",
                "Switzerland", "Syria", "Tajikistan", "Tanzania",
                "Dodoma (legislative)", "Thailand", "Timor-Leste",
                "Togo", "Tonga", "Trinidad and Tobago", "Tunisia",
                "Turkey", "Turkmenistan", "Tuvalu", "Uganda",
                "Ukraine", "United Arab Emirates", "United Kingdom", 
                "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela",
                "Vietnam", "Yemen", "Zambia", "Zimbabwe"
  ]
end
